import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import SessionProviderClient from "./providers/SessionProviderClient";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
// import { WishlistProvider } from "./WishlistContext";
import "react-toastify/dist/ReactToastify.css";
import AppProviders from "./providers/AppProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Artiory",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <SessionProviderClient session={session}>
        {/* <CartProvider> */}
          <AppProviders>
           {/* <WishlistProvider> */}
            <Header />
            <main className="flex-grow">
              {children}
            </main>     
            <Footer />
            </AppProviders>
          {/* </WishlistProvider> */}
          {/* </CartProvider> */}
          </SessionProviderClient>
      </body>
      
    </html>
  );
}
